### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by chadaaland** [MoveManagementGroup/helpmemoveit-apache-php#1]
...

**Comment by TheDude70** [comment]
Does seem so. Getting HTTP Error 503. Will need @AustinMaddox to help on this to check on the server status.

**Comment by AustinMaddox** [comment]
I'm on it. Will be fixed shortly.

**Comment by AustinMaddox** [comment]
Fixed. It was a file permission issue.

**Comment by chadaaland** [comment]
thx

 

Chad Aaland

COO/CFO

Move Management Group Inc.
372 S. Eagle Road #154
Eagle, ID 83616-5908
208-639-1280 Phone
877-381-1754 Fax

 

Visual/Telephone/Video Surveys ~ Debris Pick-Ups

QC Checks ~ Transit Damage Reviews ~ Mover Training DVDs
